module.exports = {
  content: [
    "./index.html",
    "./add.html",
    "./stats.html",
    "./logs.html",
    "./settings.html",
    "./app.js",
  ],
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#262626",
        error: "#ff7351",
        "on-secondary-container": "#f0dcff",
        "error-container": "#b92902",
        outline: "#767575",
        "error-dim": "#d53d18",
        "primary-dim": "#beee00",
        "on-secondary-fixed-variant": "#7500cc",
        "surface-container-high": "#20201f",
        "primary-fixed": "#cafd00",
        "on-tertiary-container": "#5d5000",
        secondary: "#bf81ff",
        "surface-container-low": "#131313",
        "surface-container": "#1a1a1a",
        "inverse-on-surface": "#565555",
        "on-secondary": "#32005c",
        "secondary-fixed": "#e4c6ff",
        "on-primary-fixed": "#3a4a00",
        "on-error-container": "#ffd2c8",
        "secondary-fixed-dim": "#dab4ff",
        "on-error": "#450900",
        "on-primary-container": "#4a5e00",
        "surface-tint": "#f3ffca",
        "inverse-surface": "#fcf9f8",
        "on-surface-variant": "#adaaaa",
        "on-primary-fixed-variant": "#526900",
        "primary-container": "#cafd00",
        "surface-dim": "#0e0e0e",
        "on-secondary-fixed": "#4e008a",
        "on-background": "#ffffff",
        "tertiary-dim": "#edd13a",
        "surface-bright": "#2c2c2c",
        primary: "#f3ffca",
        "tertiary-fixed-dim": "#edd13a",
        "on-tertiary-fixed": "#483d00",
        surface: "#0e0e0e",
        "inverse-primary": "#516700",
        "on-tertiary": "#665800",
        "tertiary-fixed": "#fce047",
        "secondary-container": "#7701d0",
        "on-tertiary-fixed-variant": "#685900",
        background: "#0e0e0e",
        "tertiary-container": "#fce047",
        tertiary: "#ffeea5",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#9c42f4",
        "surface-container-highest": "#262626",
        "on-surface": "#ffffff",
        "on-primary": "#516700",
        "primary-fixed-dim": "#beee00",
        "outline-variant": "#484847",
      },
      fontFamily: {
        headline: ["system-ui", "-apple-system", "BlinkMacSystemFont", "\"Segoe UI\"", "sans-serif"],
        body: ["system-ui", "-apple-system", "BlinkMacSystemFont", "\"Segoe UI\"", "sans-serif"],
        label: ["system-ui", "-apple-system", "BlinkMacSystemFont", "\"Segoe UI\"", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
};
